; ----------------------------------------------------
;
; SIMON SAYS ASSEMBLY CODE
; DOMINIC GAIERO AND ELIZABETH DAVIS
;
; DESCRIPTION:
; 
; ----------------------------------------------------

.EQU SWITCHES = 0x20
.EQU RAND = 0x22
.EQU BTN_STATUS = 0x35
.EQU INT_BTN_PRESS = 0x39
.EQU LEDS = 0x40
.EQU LED_STATUS = 0x41
.EQU INT_LED_SET = 0x37
.EQU INT_LED_CLR = 0x38
.EQU SEVEN_SEG = 0x81

;--------------------------------------------------------------------------
;-- .ORG used in code segment
;--------------------------------------------------------------------------
.CSEG
.ORG 0x01                ; SET THE DATA SEGMENT COUNTER TO 0x01

MOV r1, 0x00 ; MOVES 0x00 INTO R1 (R1 HOLDS THE LOCATION OF THE VALUES IN THE SCRATCH RAM

MAIN: IN R0, RAND ; TAKES IN A VALUE FROM THE RANDOM NUMBER GENERATOR
AND R0, 0x0F ; MASKS THE UPPER FOUR BITS OF THE VALUE FROM THE RANDOM NUMBER GENERATOR 
ST R0,(R1) ; STORES THE VALUE FROM THE RANDOM NUMBER GENERATOR AT LOCATION 0 IN THE SCRATCH RAM
CALL SHOW_LED ; CALLS THE SHOW LED SUBROUTINE
CALL READ_VALUES ; CALLS THE READ_VALUES SUBROUTINE
ADD R1, 0x01 ; ADDS ONE TO R1 TO STEP THROUGH THE SCRATCH RAM
CMP R1, 0xC8 ; COMPARES R1 WITH DECIMAL 200
BREQ PROGRAM_END ; IF R1 IS 200 THE PROGRAM WILL END
BRN MAIN ; ELSE IT WILL CONTINUE TO LOOP


SHOW_LED:
MOV R2,0x00
MOV R6,0x01
LD R3,(R2)
OUT R3, LED_STATUS; OUTPUT THE VALUE IN R3 TO THE SIMON SAYS LEDS
OUT R5, INT_LED_SET
;DELAY 0.25 SECONDS HERE
OUT R5, INT_LED_CLR
CMP R1,R2
;ADD TO R2 IF NOT EQUAL
;RETURN OTHERWISE

READ_VALUES:
MOV R2,0x00
IN R5, INT_BTN_PRESS
CMP R5, 0x01
BRNE READ_VALUES
IN R4, BTN_STATUS
LD R3, (R2)
CMP R3, R4
BRNE PROGRAM_END
CMP R2,R1
; NOT EQUAL LD FROM SR LOCATION STORED IN R2 INTO R3
; IF EQUAL RETURN 



PROGRAM_END: MOV R7, 0x0F
OUT R7, LED_STATUS
; DELAY 0.25 SECONDS HERE
MOV R8, 0x00
OUT R8, LED_STATUS
; DELAY 0.25 SECONDS HERE
OUT R7, LED_STATUS
BRN MAIN

 
 
