.EQU SWITCHES    = 0x20
.EQU CHANGE_MODE = 0x22
.EQU SEVEN_SEG   = 0x81
.EQU RED_LED     = 0x52
.EQU GRN_LED     = 0x53
.EQU BLU_LED     = 0x54


.CSEG
.ORG 0x01

MAIN:
MOV R2, 0x00

CHECK_RED_VALUE_BTN_PRESS:
OUT R2, SEVEN_SEG ; SHOWS WHICH VALUE IS BEING OUTPUTTED R,G,B
IN R0, CHANGE_MODE ; TAKES IN A BUTTON PRESS
CMP R0, 0x01 ; CHECKS IF THERE WAS NO BUTTON PRESS
BRNE CHECK_RED_VALUE_BTN_PRESS ; IF THERE WAS NO BUTTON PRESS THEN IT CONTINUES TO POLL
CALL INCREMENT
IN R7, SWITCHES ; TAKES IN THE VALUE OF THE SWITCHES

CHECK_GRN_VALUE_BTN_PRESS: ; SAME AS ABOVE (GREEN)
OUT R2, SEVEN_SEG
IN R0, CHANGE_MODE
CMP R0, 0x01
BRNE CHECK_GRN_VALUE_BTN_PRESS
CALL INCREMENT
IN R8, SWITCHES

CHECK_BLU_VALUE_BTN_PRESS: ; SAME AS ABOVE (BLUE)
OUT R2, SEVEN_SEG
IN R0, CHANGE_MODE
CMP R0, 0x01
BRNE CHECK_BLU_VALUE_BTN_PRESS
IN R9, SWITCHES

OUT R7, RED_LED ; OUTPUTS THE SWITCH VALUE TO THE RED LED
OUT R8, GRN_LED ; OUTPUTS THE SWITCH VALUE TO THE GREEN LED
OUT R9, BLU_LED ; OUTPUTS THE SWITCH VALUE TO THE BLUE LED

BRN MAIN

INCREMENT:
ADD R2, 0x01 ; INCREMENTS
RET
