; ----------------------------------------------------
;
; SW ASSIGNMENT No. 8 PART 2
; DOMINIC GAIERO AND ELIZABETH DAVIS
;
; DESCRIPTION:
; A PROGRAM THAT OUTPUTS THE MOST RECENT VALUE RECIEVED
; ON THE SWITCHES TO THE LEDS WHEN IT RECEIVES AN INTERRUPT.
; WHEN THE SWITCHES OUTPUT THE SAME VALUE ON TWO INTERRUPTS IN
; A ROW THE PROGRAM WILL STOP OUTPUTTING VALUES (ie TURN OFF THE
; LEDS) UNTIL BUTTON(0) IS PRESSED. THE PROGRAM THEN CONTINUES AS
; NORMAL.
; ----------------------------------------------------

.EQU IN_PORT = 0x9A
.EQU BUTTONS = 0x9B
.EQU LEDS = 0x42
.EQU SWITCHES = 0x20

;--------------------------------------------------------------------------
;-- .ORG used in code segment
;--------------------------------------------------------------------------
.CSEG
.ORG 0x01                ; SET THE DATA SEGMENT COUNTER TO 0x01

MOV R3, 0x00
MOV R2, 0x00
MOV R1, 0x00

BRN MAIN

ISR: CMP R2, R0 ; COMAPRE CURRENT VALUE TO PREVIOUS VALUE
BRNE VALUES_NOT_EQUAL ; 
VALUES_EQUAL: ADD R1, 0x01
RETIE
VALUES_NOT_EQUAL: MOV R2, R0
MOV R3, 0x01
RETIE

CHECK_BTN: 
CLI
MOV R0, 0x00
OUT R0, LEDS
IN R10, BUTTONS
AND R10, 0x01
CMP R10, 0x01
BRNE CHECK_BTN

MAIN: SEI ; ENABLES INTERRUPTS
MOV R10, 0x00
IN R0, SWITCHES
CMP R1, 0x01
BREQ CHECK_BTN
CMP R3, 0x01
BRNE MAIN
OUT R0, LEDS
MOV R3, 0x00
BRN MAIN

.ORG 0x3FF
VECTOR: BRN ISR
