; ----------------------------------------------------
;
; HW ASSIGNMENT No. 2
; DOMINIC GAIERO AND ELIZABETH DAVIS
;
; DESCRIPTION:
; PLAY MARIO COIN TOSS SOUND ON SPEAKER_PORT
; ----------------------------------------------------

.EQU SPEAKER_PORT = 0x36

;--------------------------------------------------------------------------
;-- .ORG used in code segment
;--------------------------------------------------------------------------
.CSEG
.ORG 0x40    ; set the data segment counter to 0x40

MOV R0, 0x0C ; FREQUENCY = 1976Hz
OUT R0, SPEAKER_PORT

LOOP1:       ; HIGHEST LOOP
MOV R2,0xFE  ; MOVES 0XFE INTO R2. INCREMENT COUNTER ASSOCIATED WITH LOOP2
             ; USED FOR RESETING
LOOP2:       ; MIDDLE LOOP
MOV R3,0xFF  ; MOVES 0XFF INTO R1. INCREMENT COUNTER ASSOCIATED WITH LOOP3

LOOP3:       ; LOWEST LOOP
SUB R3,0x01  ; DECREMENTS THE COUNTER
BRNE LOOP3   ; CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

SUB R2, 0x01 ; DECREMENTS THE COUNTER
BRNE LOOP2   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP


SUB R1, 0x01 ; DECREMENTS THE COUNTER 
BRNE LOOP1   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

MOV R0, 0x11 ; FREQUENCY = 2637Hz
OUT R0, SPEAKER_PORT

LOOP1:       ; HIGHEST LOOP
MOV R2,0xFE  ; MOVES 0XFE INTO R2. INCREMENT COUNTER ASSOCIATED WITH LOOP2
             ; USED FOR RESETING
LOOP2:       ; MIDDLE LOOP
MOV R3,0xFF  ; MOVES 0XFF INTO R1. INCREMENT COUNTER ASSOCIATED WITH LOOP3

LOOP3:       ; LOWEST LOOP
SUB R3,0x01  ; DECREMENTS THE COUNTER
BRNE LOOP3   ; CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

SUB R2, 0x01 ; DECREMENTS THE COUNTER
BRNE LOOP2   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP


SUB R1, 0x01 ; DECREMENTS THE COUNTER 
BRNE LOOP1   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

LOOP1:       ; HIGHEST LOOP
MOV R2,0xFE  ; MOVES 0XFE INTO R2. INCREMENT COUNTER ASSOCIATED WITH LOOP2
             ; USED FOR RESETING
LOOP2:       ; MIDDLE LOOP
MOV R3,0xFF  ; MOVES 0XFF INTO R1. INCREMENT COUNTER ASSOCIATED WITH LOOP3

LOOP3:       ; LOWEST LOOP
SUB R3,0x01  ; DECREMENTS THE COUNTER
BRNE LOOP3   ; CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

SUB R2, 0x01 ; DECREMENTS THE COUNTER
BRNE LOOP2   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP


SUB R1, 0x01 ; DECREMENTS THE COUNTER 
BRNE LOOP1   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

LOOP1:       ; HIGHEST LOOP
MOV R2,0xFE  ; MOVES 0XFE INTO R2. INCREMENT COUNTER ASSOCIATED WITH LOOP2
             ; USED FOR RESETING
LOOP2:       ; MIDDLE LOOP
MOV R3,0xFF  ; MOVES 0XFF INTO R1. INCREMENT COUNTER ASSOCIATED WITH LOOP3

LOOP3:       ; LOWEST LOOP
SUB R3,0x01  ; DECREMENTS THE COUNTER
BRNE LOOP3   ; CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

SUB R2, 0x01 ; DECREMENTS THE COUNTER
BRNE LOOP2   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP


SUB R1, 0x01 ; DECREMENTS THE COUNTER 
BRNE LOOP1   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

LOOP1:       ; HIGHEST LOOP
MOV R2,0xFE  ; MOVES 0XFE INTO R2. INCREMENT COUNTER ASSOCIATED WITH LOOP2
             ; USED FOR RESETING
LOOP2:       ; MIDDLE LOOP
MOV R3,0xFF  ; MOVES 0XFF INTO R1. INCREMENT COUNTER ASSOCIATED WITH LOOP3

LOOP3:       ; LOWEST LOOP
SUB R3,0x01  ; DECREMENTS THE COUNTER
BRNE LOOP3   ; CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

SUB R2, 0x01 ; DECREMENTS THE COUNTER
BRNE LOOP2   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP


SUB R1, 0x01 ; DECREMENTS THE COUNTER 
BRNE LOOP1   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

LOOP1:       ; HIGHEST LOOP
MOV R2,0xFE  ; MOVES 0XFE INTO R2. INCREMENT COUNTER ASSOCIATED WITH LOOP2
             ; USED FOR RESETING
LOOP2:       ; MIDDLE LOOP
MOV R3,0xFF  ; MOVES 0XFF INTO R1. INCREMENT COUNTER ASSOCIATED WITH LOOP3

LOOP3:       ; LOWEST LOOP
SUB R3,0x01  ; DECREMENTS THE COUNTER
BRNE LOOP3   ; CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

SUB R2, 0x01 ; DECREMENTS THE COUNTER
BRNE LOOP2   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP


SUB R1, 0x01 ; DECREMENTS THE COUNTER 
BRNE LOOP1   ;CHECKS THE ZERO FLAG TO SEE IF THE PROGRAM CAN MOVE TO THE NEXT LOOP

MOV R0, 0x00
OUT R0, SPEAKER_PORT