# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.cache/wt [current_project]
set_property parent.project_path C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.srcs/sources_1/new/ALU.vhd
  C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.srcs/sources_1/new/ALU_MUX.vhd
  C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.srcs/sources_1/new/CONTROL_UNIT.vhd
  C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.srcs/sources_1/new/REG_FILE.vhd
  C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.srcs/sources_1/new/REG_MUX.vhd
  C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.srcs/sources_1/new/pc_mux.vhd
  C:/Users/edavis/Documents/CPE_233/RAT_5/ASSEMBLY/prog_rom.vhd
  C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.srcs/sources_1/new/program_counter.vhd
  C:/Users/edavis/Documents/CPE_233/RAT_5/VIVADO/RAT_5.srcs/sources_1/new/RAT_MCU.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top RAT_MCU -part xc7a35tcpg236-1


write_checkpoint -force -noxdef RAT_MCU.dcp

catch { report_utilization -file RAT_MCU_utilization_synth.rpt -pb RAT_MCU_utilization_synth.pb }
