; ----------------------------------------------------
;
; SW ASSIGNMENT No. 7 PART 2
; DOMINIC GAIERO AND ELIZABETH DAVIS
;
; DESCRIPTION:
; MULTIPLIES TWO 8 BIT NUMBERS TOGETHER AND SEPERATES THE
; EIGHTEEN BIT RESULT INTO A HIGH 8 BITS AND A LOW 8 BITS
; ----------------------------------------------------
.CSEG
.ORG 0x01
BRN MAIN

MULTIPLY_VAL: ADD R0,R1
SUB R2, 0x01
BRCC SKIP_ADD_UPPER
ADD R3, 0x01
SKIP_ADD_UPPER: CMP R2, 0x00
BRCC RET
BRN MULTIPLY_VAL


MAIN:
MOV R2, 0x00
MOV R3, 0x00
IN R0, 0x20
CMP R0, 0x00
BREQ OUTPUT_VALUE
IN R1, 0x21
CMP R0, 0x00
BREQ OUTPUT_VALUE

MOV R2, R1
MOV R5, 0x00
CALL MULTIPLY_VAL

OUTPUT_VALUE: R3, 0x41
OUT R2, 0x42
